Dev
n1kolayvas1lev/PythonPY110-exam pull request #1
Opened 2021-12-13 10:12 UTC by n1kolayvas1lev

Зачётное задание по курсу PythonPY110
Васильев Николай Георгиевич

2021-12-14 18:43 UTC, aeksei requested changes
Исправить генерацию случайных книг

2021-12-14 18:43 UTC, aeksei commented on main.py
> +#    books.readline(n)
```python
import random

with open('books.txt', 'r', encoding='utf-8') as books:
    return random.choice(books.readlines())
```

2021-12-14 20:40 UTC, n1kolayvas1lev commented
У меня невыносимые проблемы с аннотацией типов. Например, стр. 33, при попытке написать нечто вроде:
def year(): -> int:
    return random.randint(900, 2021)
Я получаю ошибку, гласящую, что return находится вне функции. Я пытался донести своим "-> int", что желаю видеть на выходе у функции целое число. При этом контекстные подсказки, отображают аннотацию вполне правильно. Я совершенно не понимаю, что я делаю не так.

2021-12-23 17:09 UTC, aeksei requested changes
- [ ] добавить аннотацию типов
- [ ] добавить документацию к функциям
- [x] заменить два момента на list comprehension (на них не могу дать указание из-за технических особенностей, а не из вредности)

После исправлений можно сливать ветку и закрывать pull request

---

Если стоит статус **Changes requested**, то нужно в данную ветку внести обязательные изменения, которые представлены ниже. Если выше представлены комментарии, то они носят рекомендательный характер.
После нужно сделать "push", тогда коммиты с изменениями сразу попадут в "pull request".

2021-12-23 18:37 UTC, merged

2021-12-23 18:39 UTC, n1kolayvas1lev commented
Готово.